### ISSUE TITLE
Can-Be-Played Checklist

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [Spesships/Spesships#1]
![spesships_icon](https://user-images.githubusercontent.com/67359748/174435929-905b5235-6574-4788-8b18-9b9ef54034d9.png)

# Description
The basic things I should prepare before the game is Can-Be-Played

### Jobs
* [ ] - Leaders
* [ ] - Engineers
* [ ] - Doctors
* [ ] - Officers
* [ ] - Loadouts for each job

### Mapping
* [ ] - Test Map
* [ ] - Cogs, the first official map

### Server Stuff
* [ ] - Unique rules.txt
* [ ] - Get listed on the server hub

### Server Stuff
* [ ] - Find a suitable server host
* [ ] - Setup a Content Delivery Network
* [ ] - Setup Watchdog
* [ ] - PostgresSQL
